// ─── CATEGORIES ────────────────────────────────────────────────────────────────
export const CATS = [
  {id:"local",    label:"Local",     desc:"Stories from your community"},
  {id:"world",    label:"World",     desc:"Global progress & good news"},
  {id:"discover", label:"Discover",  desc:"Science, tech & exploration"},
  {id:"wellness", label:"Wellness",  desc:"Health breakthroughs & wellbeing"},
  {id:"nature",   label:"Nature",    desc:"Wildlife, conservation & the planet"},
  {id:"community",label:"Community", desc:"People helping people"},
  {id:"ideas",    label:"Ideas",     desc:"Creativity, arts & innovation"},
  {id:"politics", label:"Politics",  desc:"Bipartisan wins & civic progress"},
];

// ─── STORIES ───────────────────────────────────────────────────────────────────
export const STORIES = [
  {id:1,  category:"nature",    tag:"Nature",    title:"Snow Leopard Cubs Spotted Thriving in Himalayan Reserve",          summary:"A decade of conservation work is paying off. Wildlife trackers documented a mother and three healthy cubs — the largest litter on record in the region.",              body:"Conservation teams working across the Himalayan corridor have confirmed the sighting of a snow leopard mother and three cubs in a protected reserve, marking the largest recorded litter in the region's history. The finding follows a ten-year breeding protection initiative that limited human encroachment on key habitat corridors.",           source:"Wildlife Conservation Society",   time:"2h ago",  readTime:"3 min", loves:2847, radius:0,  moodTags:["wildlife","recovery","milestone","nature"]},
  {id:2,  category:"discover",  tag:"Discover",  title:"New Battery Technology Could Make EVs Charge in Under Five Minutes",summary:"MIT researchers have developed a solid-state battery that charges ten times faster than current technology while lasting significantly longer.",                    body:"A team at MIT has published results showing a solid-state battery architecture capable of reaching 80% charge in under five minutes while retaining 90% capacity after 1,000 cycles. The breakthrough addresses the two biggest barriers to EV adoption — charge time and longevity — simultaneously.",                                              source:"MIT News",                         time:"4h ago",  readTime:"4 min", loves:1923, radius:0,  moodTags:["breakthrough","innovation","future"]},
  {id:3,  category:"community", tag:"Community", title:"The Teenager Who Built a Tutoring Platform for 50,000 Students",   summary:"What started as a homework help Discord server has grown into a nonprofit serving students across 40 countries, founded by 17-year-old Maya Chen.",             body:"When Maya Chen posted a homework help channel to Discord two years ago, she expected a few classmates. Today, the platform she built — entirely self-taught — serves 50,000 students across 40 countries.",                                                                                                                                       source:"Good Morning America",             time:"5h ago",  readTime:"5 min", loves:4102, radius:25, moodTags:["hero","achievement","kindness","community"]},
  {id:4,  category:"wellness",  tag:"Wellness",  title:"Breakthrough Depression Treatment Shows 80% Remission in Trials",  summary:"A targeted magnetic therapy has cleared Phase 3 trials with remarkable results, offering real hope for millions who haven't responded to traditional treatments.", body:"The therapy, known as deep TMS, achieved an 80% remission rate in a 600-person Phase 3 trial — a number that far exceeds the 40-60% range typical of current first-line treatments.",                                                                                                                                                                source:"New England Journal of Medicine",  time:"6h ago",  readTime:"6 min", loves:5611, radius:0,  moodTags:["breakthrough","progress","future"]},
  {id:5,  category:"world",     tag:"World",     title:"Atlantic Coral Reefs Show First Signs of Recovery in Thirty Years", summary:"Marine biologists are cautiously optimistic after new surveys found juvenile coral colonies in areas that were bleached just eight years ago.",               body:"A comprehensive NOAA survey of the Florida Reef Tract has identified juvenile coral colonies establishing themselves in sections previously declared ecologically dead following the 2016 mass bleaching event.",                                                                                                                                      source:"NOAA",                             time:"7h ago",  readTime:"4 min", loves:3388, radius:0,  moodTags:["recovery","nature","environment","progress"]},
  {id:6,  category:"politics",  tag:"Politics",  title:"Senate Passes Sweeping Veterans Mental Health Expansion, 94 to 4", summary:"In a rare show of bipartisan unity, the bill expands VA mental health services more broadly than any legislation in two decades.",                            body:"The Veterans Mental Health Modernization Act passed the Senate 94-4 following months of quiet, cross-party negotiations. The bill expands telehealth access, adds 3,000 new VA counselor positions.",                                                                                                                                                 source:"Associated Press",                 time:"9h ago",  readTime:"3 min", loves:7240, radius:0,  moodTags:["progress","milestone","victory","kindness"]},
  {id:7,  category:"local",     tag:"Local",     title:"A Shuttered Mall Becomes the Town's Beating Heart",                summary:"Three years after closing, a former shopping center reopens as a community farm, co-working hub, and arts space — funded entirely by local crowdfunding.",    body:"The Millbrook Commons mall, vacant since 2021, has been transformed by a coalition of local residents into a mixed-use community space including an urban farm, a 60-desk co-working space, and a community kitchen.",                                                                                                                                source:"Regional News Network",            time:"11h ago", readTime:"4 min", loves:1654, radius:15, moodTags:["community","kindness","connection"]},
  {id:8,  category:"nature",    tag:"Nature",    title:"California Condor Population Reaches 500 for the First Time",      summary:"Once down to just 27 individuals, the condor has hit a historic milestone after 40 years of dedicated recovery programs.",                                    body:"The California condor has now crossed the 500 individual milestone. Wildlife biologists confirmed the population count this week, calling it one of the most successful recovery programs in conservation history.",                                                                                                                                   source:"US Fish & Wildlife Service",       time:"12h ago", readTime:"5 min", loves:2991, radius:50, moodTags:["milestone","record","wildlife","victory","nature"]},
  {id:9,  category:"discover",  tag:"Discover",  title:"Webb Telescope Detects Life Chemistry Signatures on Distant Exoplanet",summary:"Astronomers have found dimethyl sulfide in the atmosphere of K2-18b — a molecule produced on Earth almost exclusively by living organisms.",           body:"The James Webb Space Telescope has detected what appears to be dimethyl sulfide in the atmosphere of K2-18b, a super-Earth in the habitable zone of its host star. Researchers describe it as the most compelling biosignature ever observed beyond our solar system.",                                                                               source:"NASA / ESA",                       time:"1d ago",  readTime:"7 min", loves:9812, radius:0,  moodTags:["breakthrough","innovation","future","achievement"]},
  {id:10, category:"community", tag:"Community", title:"A Viral Campaign Just Added 2.3 Million Organ Donors to the Registry",summary:"A 12-year-old's tribute video to her donor sparked a social media movement that produced one of the largest single sign-up surges on record.",         body:"After Priya Nair posted a video tribute to the donor who saved her life, the clip reached 40 million views in four days. UNOS reported a 600% spike in registry sign-ups with 2.3 million new donors added across the United States.",                                                                                                               source:"UNOS",                             time:"1d ago",  readTime:"4 min", loves:6730, radius:30, moodTags:["kindness","community","milestone","connection","record"]},
  {id:11, category:"local",     tag:"Local",     title:"Free Bus Pilot Cuts Downtown Car Traffic by 34 Percent",            summary:"Six months after making all buses free, the city reports dramatic air quality improvements and record ridership.",                                            body:"A six-month review found a 34% reduction in downtown vehicle traffic, a 22% improvement in air quality index scores, and record daily ridership exceeding pre-pandemic highs by 40%.",                                                                                                                                                                source:"City Transit Authority",           time:"1d ago",  readTime:"3 min", loves:2100, radius:10, moodTags:["progress","community","environment","future"]},
  {id:12, category:"wellness",  tag:"Wellness",  title:"Twenty-Minute Daily Walks Reduce Dementia Risk by Forty Percent",  summary:"One of the largest longitudinal studies of its kind found that consistent moderate walking dramatically outperforms medication for dementia prevention.",  body:"A 15-year follow-up study tracking 48,000 adults aged 60+ found that those who walked at a moderate pace for 20 minutes daily showed a 40% lower incidence of dementia onset compared to sedentary controls.",                                                                                                                                          source:"The Lancet",                       time:"2d ago",  readTime:"5 min", loves:8842, radius:0,  moodTags:["progress","calm","future","milestone"]},
];
